/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/

package com.banquet.acs_banquet1.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Service;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;

@Service
public class Acs_banquet1QueryExecutorServiceImpl implements Acs_banquet1QueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(Acs_banquet1QueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("acs_banquet1WMQueryExecutor")
    private WMQueryExecutor queryExecutor;


}


