/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.banquet.acs_banquet.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetCat4ProductResponse implements Serializable {


    @ColumnAlias("p_name")
    private String pname;

    @ColumnAlias("p_description")
    private String pdescription;

    @ColumnAlias("p_rating")
    private Integer prating;

        @JsonView(BlobAsUrlView.class)
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("p_picture")
    private byte[] ppicture;

    @ColumnAlias("cat_name")
    private String catName;

    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public String getPdescription() {
        return this.pdescription;
    }

    public void setPdescription(String pdescription) {
        this.pdescription = pdescription;
    }

    public Integer getPrating() {
        return this.prating;
    }

    public void setPrating(Integer prating) {
        this.prating = prating;
    }

    public byte[] getPpicture() {
        return this.ppicture;
    }

    public void setPpicture(byte[] ppicture) {
        this.ppicture = ppicture;
    }

    public String getCatName() {
        return this.catName;
    }

    public void setCatName(String catName) {
        this.catName = catName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetCat4ProductResponse)) return false;
        final GetCat4ProductResponse getCat4productResponse = (GetCat4ProductResponse) o;
        return Objects.equals(getPname(), getCat4productResponse.getPname()) &&
                Objects.equals(getPdescription(), getCat4productResponse.getPdescription()) &&
                Objects.equals(getPrating(), getCat4productResponse.getPrating()) &&
                Objects.equals(getPpicture(), getCat4productResponse.getPpicture()) &&
                Objects.equals(getCatName(), getCat4productResponse.getCatName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPname(),
                getPdescription(),
                getPrating(),
                getPpicture(),
                getCatName());
    }
}
