/*Copyright (c) 2017-2018 asyst.co.id All Rights Reserved.
 This software is the confidential and proprietary information of asyst.co.id You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with asyst.co.id*/
package com.banquet.acs_banquet.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetPackagePictResponse implements Serializable {


        @JsonView(BlobAsUrlView.class)
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("pict")
    private byte[] pict;

    @ColumnAlias("p_name")
    private String pname;

    @ColumnAlias("p_rating")
    private Integer prating;

    public byte[] getPict() {
        return this.pict;
    }

    public void setPict(byte[] pict) {
        this.pict = pict;
    }

    public String getPname() {
        return this.pname;
    }

    public void setPname(String pname) {
        this.pname = pname;
    }

    public Integer getPrating() {
        return this.prating;
    }

    public void setPrating(Integer prating) {
        this.prating = prating;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetPackagePictResponse)) return false;
        final GetPackagePictResponse getPackagePictResponse = (GetPackagePictResponse) o;
        return Objects.equals(getPict(), getPackagePictResponse.getPict()) &&
                Objects.equals(getPname(), getPackagePictResponse.getPname()) &&
                Objects.equals(getPrating(), getPackagePictResponse.getPrating());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPict(),
                getPname(),
                getPrating());
    }
}
